version: "2"
linters:
  default: all
  disable:
    ### deprecated, archived or obsolette by authors
    - paralleltest
    - wsl
    ### disabled by me
    - depguard
    - exhaustruct
    - godot
    - godox
    - ireturn
    - varnamelen
    - wrapcheck
    - noinlineerr
  settings:
    funlen:
      ignore-comments: true
    revive:
      rules:
        - name: exported
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1000
  exclusions:
    generated: lax
    rules:
      - linters:
          - err113
        path: _test\.go
    paths:
      - debug.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - debug.go
      - third_party$
      - builtin$
      - examples$
