linters-settings:
  funlen:
    ignore-comments: true
  revive:
    rules:
      - name: exported
        disabled: true
  stylecheck:
    checks: ["all", "-ST1000"]
linters:
  enable-all: true
  disable:
    ### deprecated, archived or obsolette by authors
    - paralleltest
    - tenv
    ### disabled by me
    - depguard
    - exhaustruct
    - godot
    - godox
    - ireturn
    - varnamelen
    - wrapcheck
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - err113
  exclude-files:
    - cmd/debug/main.go
