require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - tmp/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - bin/*
  NewCops: enable
  SuggestExtensions: true

# Layout
Layout/LineLength:
  Max: 120

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

# Lint
Lint/MissingSuper:
  Enabled: false

# Metrics
Metrics/BlockLength:
  Exclude:
  - app/admin/**/*
  - lib/tasks/auto_annotate_models.rake
  - spec/**/*

# RSpec
RSpec/SubjectStub: # delme
  Enabled: false

RSpec/NamedSubject: # delme
  Enabled: false

RSpec/MissingExampleGroupArgument: # delme
  Enabled: false

RSpec/VerifiedDoubles: # ???
  Enabled: false

RSpec/MessageChain: # ???
  Enabled: false

# Rails
Rails/SkipsModelValidations:
  AllowedMethods: [touch]

Rails/FilePath:
  EnforcedStyle: arguments

Rails/HasAndBelongsToMany:
  Enabled: false

# Style
Style/Documentation:
  Enabled: false
