require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - tmp/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - bin/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
  - spec/**/*
  - config/initializers/simple_form_bootstrap.rb

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

RSpec/InstanceVariable:
  Exclude:
    - spec/support/shared_examples/controller.rb

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/ExpectInHook:
  Enabled: false

RSpec/MissingExampleGroupArgument:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/SharedExamples:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false
