// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject

package wire

import (
	"context"
	repository4 "github.com/tksasha/balance/internal/app/balance/repository"
	service4 "github.com/tksasha/balance/internal/app/balance/service"
	handlers3 "github.com/tksasha/balance/internal/app/cash/handlers"
	repository3 "github.com/tksasha/balance/internal/app/cash/repository"
	service3 "github.com/tksasha/balance/internal/app/cash/service"
	repository5 "github.com/tksasha/balance/internal/app/category/repository"
	service5 "github.com/tksasha/balance/internal/app/category/service"
	handlers5 "github.com/tksasha/balance/internal/app/categoryreport/handlers"
	repository7 "github.com/tksasha/balance/internal/app/categoryreport/repository"
	service7 "github.com/tksasha/balance/internal/app/categoryreport/service"
	"github.com/tksasha/balance/internal/app/index/handler"
	handlers4 "github.com/tksasha/balance/internal/app/item/handlers"
	repository6 "github.com/tksasha/balance/internal/app/item/repository"
	service6 "github.com/tksasha/balance/internal/app/item/service"
	"github.com/tksasha/balance/internal/backoffice/cash/handlers"
	"github.com/tksasha/balance/internal/backoffice/cash/repository"
	"github.com/tksasha/balance/internal/backoffice/cash/service"
	handlers2 "github.com/tksasha/balance/internal/backoffice/category/handlers"
	repository2 "github.com/tksasha/balance/internal/backoffice/category/repository"
	service2 "github.com/tksasha/balance/internal/backoffice/category/service"
	"github.com/tksasha/balance/internal/db"
	"github.com/tksasha/balance/internal/db/nameprovider"
	"github.com/tksasha/balance/internal/server"
	"github.com/tksasha/balance/internal/server/config"
	"github.com/tksasha/balance/internal/server/middlewares"
	"github.com/tksasha/balance/internal/server/routes"
)

// Injectors from wire.go:

func InitializeServer() *server.Server {
	configConfig := config.New()
	contextContext := context.Background()
	nameProvider := nameprovider.New()
	sqlDB := db.Open(contextContext, nameProvider)
	repositoryRepository := repository.New(sqlDB)
	serviceService := service.New(repositoryRepository)
	createHandler := handlers.NewCreateHandler(serviceService)
	deleteHandler := handlers.NewDeleteHandler(serviceService)
	editHandler := handlers.NewEditHandler(serviceService)
	listHandler := handlers.NewListHandler(serviceService)
	newHandler := handlers.NewNewHandler()
	updateHandler := handlers.NewUpdateHandler(serviceService)
	repository8 := repository2.New(sqlDB)
	service8 := service2.New(repository8)
	handlersCreateHandler := handlers2.NewCreateHandler(service8)
	handlersDeleteHandler := handlers2.NewDeleteHandler(service8)
	handlersEditHandler := handlers2.NewEditHandler(service8)
	handlersListHandler := handlers2.NewListHandler(service8)
	handlersUpdateHandler := handlers2.NewUpdateHandler(service8)
	repository9 := repository3.New(sqlDB)
	service9 := service3.New(repository9)
	editHandler2 := handlers3.NewEditHandler(service9)
	updateHandler2 := handlers3.NewUpdateHandler(service9)
	repository10 := repository4.New(sqlDB)
	service10 := service4.New(repository10)
	repository11 := repository5.New(sqlDB)
	service11 := service5.New(repository11)
	handlerHandler := handler.New(service10, service9, service11)
	repository12 := repository6.New(sqlDB)
	service12 := service6.New(repository12, repository11)
	createHandler2 := handlers4.NewCreateHandler(service12, service11)
	editHandler3 := handlers4.NewEditHandler(service12, service11)
	indexHandler := handlers4.NewIndexHandler(service12)
	updateHandler3 := handlers4.NewUpdateHandler(service12, service11)
	repository13 := repository7.New(sqlDB)
	service13 := service7.New(repository13)
	showHandler := handlers5.NewShowHandler(service13)
	routesRoutes := routes.New(createHandler, deleteHandler, editHandler, listHandler, newHandler, updateHandler, handlersCreateHandler, handlersDeleteHandler, handlersEditHandler, handlersListHandler, handlersUpdateHandler, editHandler2, updateHandler2, handlerHandler, createHandler2, editHandler3, indexHandler, updateHandler3, showHandler)
	v := middlewares.New()
	serverServer := server.New(configConfig, routesRoutes, v)
	return serverServer
}
