// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject

package wire

import (
	"context"
	handlers2 "github.com/tksasha/balance/internal/cash/handlers"
	"github.com/tksasha/balance/internal/cash/repository"
	"github.com/tksasha/balance/internal/cash/service"
	"github.com/tksasha/balance/internal/config"
	"github.com/tksasha/balance/internal/db"
	"github.com/tksasha/balance/internal/handlers"
	"github.com/tksasha/balance/internal/handlers/cashes"
	"github.com/tksasha/balance/internal/middlewares"
	"github.com/tksasha/balance/internal/providers"
	"github.com/tksasha/balance/internal/repositories"
	"github.com/tksasha/balance/internal/routes"
	"github.com/tksasha/balance/internal/server"
	"github.com/tksasha/balance/internal/services"
)

// Injectors from wire.go:

func InitializeServer() *server.Server {
	configConfig := config.New()
	contextContext := context.Background()
	dbNameProvider := providers.NewDBNameProvider()
	sqlDB := db.Open(contextContext, dbNameProvider)
	cashRepository := repositories.NewCashRepository(sqlDB)
	cashService := services.NewCashService(cashRepository)
	createHandler := cashes.NewCreateHandler(cashService)
	cashDeleteHandler := handlers.NewCashDeleteHandler(cashService)
	cashEditHandler := handlers.NewCashEditHandler(cashService)
	repositoryRepository := repository.New(sqlDB)
	serviceService := service.New(repositoryRepository)
	listHandler := handlers2.NewListHandler(serviceService)
	newHandler := cashes.NewNewHandler()
	cashUpdateHandler := handlers.NewCashUpdateHandler(cashService)
	categoryRepository := repositories.NewCategoryRepository(sqlDB)
	categoryService := services.NewCategoryService(categoryRepository)
	categoryCreateHandler := handlers.NewCategoryCreateHandler(categoryService)
	categoryDeleteHandler := handlers.NewCategoryDeleteHandler(categoryService)
	categoryEditHandler := handlers.NewCategoryEditHandler(categoryService)
	categoryListHandler := handlers.NewCategoryListHandler(categoryService)
	categoryUpdateHandler := handlers.NewCategoryUpdateHandler(categoryService)
	indexPageHandler := handlers.NewIndexPageHandler(categoryService)
	itemRepository := repositories.NewItemRepository(sqlDB)
	itemService := services.NewItemService(itemRepository, categoryRepository)
	itemCreateHandler := handlers.NewItemCreateHandler(itemService)
	itemEditHandler := handlers.NewItemEditHandler(itemService)
	itemListHandler := handlers.NewItemListHandler(itemService)
	itemUpdateHandler := handlers.NewItemUpdateHandler(itemService)
	routesRoutes := routes.New(createHandler, cashDeleteHandler, cashEditHandler, listHandler, newHandler, cashUpdateHandler, categoryCreateHandler, categoryDeleteHandler, categoryEditHandler, categoryListHandler, categoryUpdateHandler, indexPageHandler, itemCreateHandler, itemEditHandler, itemListHandler, itemUpdateHandler)
	v := middlewares.New()
	serverServer := server.New(configConfig, routesRoutes, v)
	return serverServer
}
