// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject

package server

import (
	"github.com/tksasha/balance/internal/config"
	"github.com/tksasha/balance/internal/handlers"
	"github.com/tksasha/balance/internal/middlewares"
	"github.com/tksasha/balance/internal/repositories"
)

// Injectors from wire.go:

func InitializeServer() *Server {
	configConfig := config.New()
	indexPageHandler := handlers.NewIndexPageHandler()
	itemRepository := repositories.NewItemRepository()
	createItemHandler := handlers.NewCreateItemHandler(itemRepository)
	recoveryMiddleware := middlewares.NewRecoveryMiddleware()
	currencyMiddleware := middlewares.NewCurrencyMiddleware()
	router := NewRouter(indexPageHandler, createItemHandler, recoveryMiddleware, currencyMiddleware)
	server := New(configConfig, router)
	return server
}
