// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/tksasha/balance/internal/config"
	"github.com/tksasha/balance/internal/server/app"
	"github.com/tksasha/balance/internal/server/db"
	"github.com/tksasha/balance/internal/server/middlewares"
	"github.com/tksasha/balance/internal/server/routes"
)

// Injectors from wire.go:

func Initialize() *Server {
	sqlDB := db.Open()
	appApp := app.New(sqlDB)
	configConfig := config.New()
	serveMux := routes.New(configConfig, appApp)
	handler := middlewares.New(appApp, serveMux)
	server := New(appApp, configConfig, serveMux, handler)
	return server
}
