// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/tksasha/balance/internal/config"
	"github.com/tksasha/balance/internal/handlers"
	"github.com/tksasha/balance/internal/middlewares"
	"github.com/tksasha/balance/internal/server/app"
	"github.com/tksasha/balance/internal/server/db"
)

// Injectors from wire.go:

func InitializeServer() *Server {
	configConfig := config.New()
	sqlDB := db.Open()
	appApp := app.New(sqlDB)
	indexPageHandler := handlers.NewIndexPageHandler(appApp)
	recoveryMiddleware := middlewares.NewRecoveryMiddleware()
	currencyMiddleware := middlewares.NewCurrencyMiddleware(appApp)
	router := NewRouter(indexPageHandler, recoveryMiddleware, currencyMiddleware)
	server := New(configConfig, router)
	return server
}
