// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/category_repository.go
//
// Generated by this command:
//
//	mockgen -source internal/repositories/category_repository.go -package mockedrepositories -destination mocks/repositories/category_repository.mock.go
//

// Package mockedrepositories is a generated GoMock package.
package mockedrepositories
